// Radio start/stop "beep" cue clips (see RadioBeepAssets.cpp, generated by
// tools/gen_beep_assets.py from the original TS3-plugin-era assets in old/ts/radio-sounds/) --
// the short click/chirp TFAR plays when a radio's PTT is pressed or released, distinct from the
// voice audio itself. Dropped during the C# rewrite and never carried forward into the native
// port until now.
#pragma once

#include <cstddef>
#include <cstdint>
#include <string>

namespace tfrs {
namespace voice {

struct BeepClip {
    const int16_t* samples;  // 48kHz mono
    size_t count;
};

// subtype: "sw"/"lr"/"airborne"/"dd" (matches Extension.cpp's parseSourceEffect and the wire
// protocol's radio subtype strings). Only these four radio families ever had dedicated clips in
// the original plugin -- any other subtype (phone/speaker/intercom/direct/unrecognized) returns
// nullptr, meaning "no beep for this radio type", not an error.
const BeepClip* findBeepClip(const std::string& subtype, bool local, bool start);

}  // namespace voice
}  // namespace tfrs
