// Radio start/stop "beep" cue clips (see RadioBeepAssets.cpp, generated by
// tools/gen_beep_assets.py from the original TS3-plugin-era assets in old/ts/radio-sounds/) --
// the short click/chirp TFAR plays when a radio's PTT is pressed or released, distinct from the
// voice audio itself. Dropped during the C# rewrite and never carried forward into the native
// port until now.
#pragma once

#include <cstddef>
#include <cstdint>
#include <string>

namespace tfrs {
namespace voice {

struct BeepClip {
    const int16_t* samples;  // 48kHz mono
    size_t count;
};

// subtype: "digital"/"digital_lr"/"airborne"/"dd" -- the RAW tf_subtype CfgWeapons/CfgVehicles
// config value, as carried by State::localTxState()/the RadioTxUpdate wire protocol. NOT
// Extension.cpp's parseSourceEffect vocabulary ("sw"/"lr"/etc, State.cpp's subtypeToFx() output) --
// that translation exists only for the audibility solver's DSP-effect selection and this lookup
// intentionally bypasses it (see gen_beep_assets.py). Only these four radio families ever had
// dedicated clips in the original plugin -- any other subtype (phone/speaker/intercom/direct/
// unrecognized) returns nullptr, meaning "no beep for this radio type", not an error.
const BeepClip* findBeepClip(const std::string& subtype, bool local, bool start);

}  // namespace voice
}  // namespace tfrs
