#!/usr/bin/env python3
"""One-time generator: old/ts/radio-sounds/{sw,lr,ab,dd}/{local,remote}_{start,end}.wav ->
addon/extensions/task_force_radio_pipe/src/Voice/RadioBeepAssets.cpp

Resamples every clip to 48kHz mono int16 (linear interpolation, matching the same simplification
already used elsewhere in this codebase's resampling, e.g. WasapiCaptureEngine) so the runtime
lookup table is uniform regardless of each source WAV's original format.
"""
import struct
import wave
from pathlib import Path

# This script lives at addon/extensions/task_force_radio_pipe/tools/gen_beep_assets.py.
REPO_ROOT = Path(__file__).resolve().parents[4]
SRC_ROOT = REPO_ROOT / "old" / "ts" / "radio-sounds"
OUT_PATH = (REPO_ROOT / "addon" / "extensions" / "task_force_radio_pipe" / "src" / "Voice" /
            "RadioBeepAssets.cpp")

TARGET_RATE = 48000
# subtype key (matches Extension.cpp's parseSourceEffect / the wire protocol's radio subtype
# strings) -> old radio-sounds subfolder name.
SUBTYPES = {
    "sw": "sw",
    "lr": "lr",
    "airborne": "ab",
    "dd": "dd",
}
DIRECTIONS = ["local", "remote"]
EDGES = ["start", "end"]


def read_wav_mono_i16(path: Path):
    with wave.open(str(path), "rb") as w:
        channels = w.getnchannels()
        rate = w.getframerate()
        sampwidth = w.getsampwidth()
        nframes = w.getnframes()
        raw = w.readframes(nframes)

    if sampwidth != 2:
        raise ValueError(f"{path}: unsupported sample width {sampwidth}")

    fmt = f"<{nframes * channels}h"
    samples = struct.unpack(fmt, raw)

    if channels == 1:
        mono = list(samples)
    elif channels == 2:
        mono = [(samples[i * 2] + samples[i * 2 + 1]) // 2 for i in range(nframes)]
    else:
        raise ValueError(f"{path}: unsupported channel count {channels}")

    if rate == TARGET_RATE:
        return mono

    # Linear-interpolation resample to TARGET_RATE.
    src_len = len(mono)
    if src_len == 0:
        return []
    dst_len = max(1, round(src_len * TARGET_RATE / rate))
    step = (src_len - 1) / max(1, dst_len - 1) if dst_len > 1 else 0.0
    out = []
    for i in range(dst_len):
        pos = i * step
        i0 = int(pos)
        i1 = min(i0 + 1, src_len - 1)
        frac = pos - i0
        v = mono[i0] * (1.0 - frac) + mono[i1] * frac
        out.append(int(max(-32768, min(32767, round(v)))))
    return out


def array_name(subtype_key, direction, edge):
    return f"k{subtype_key.capitalize()}{direction.capitalize()}{edge.capitalize()}"


def emit_array(lines, name, samples):
    lines.append(f"const int16_t {name}[] = {{")
    for i in range(0, len(samples), 16):
        chunk = samples[i:i + 16]
        lines.append("    " + ", ".join(str(s) for s in chunk) + ",")
    lines.append("};")
    lines.append(f"constexpr size_t {name}Count = {len(samples)};")
    lines.append("")


def main():
    lines = []
    lines.append("// GENERATED by tools/gen_beep_assets.py (run once, from the original TS3-plugin-era")
    lines.append("// assets in old/ts/radio-sounds/ -- do not hand-edit). Radio start/stop \"beep\" cue")
    lines.append("// clips, resampled to 48kHz mono int16 (see RadioBeepAssets.h). This feature was dropped")
    lines.append("// during the C# rewrite and never carried forward; only 4 of the 8 SourceEffect radio")
    lines.append("// families (sw/lr/airborne/dd) ever had dedicated clips in the original plugin.")
    lines.append("#include \"RadioBeepAssets.h\"")
    lines.append("")
    lines.append("namespace tfrs {")
    lines.append("namespace voice {")
    lines.append("")
    lines.append("namespace {")
    lines.append("")

    entries = []  # (subtype_key, direction, edge, array_name)
    total_samples = 0
    for subtype_key, folder in SUBTYPES.items():
        for direction in DIRECTIONS:
            for edge in EDGES:
                wav_path = SRC_ROOT / folder / f"{direction}_{edge}.wav"
                samples = read_wav_mono_i16(wav_path)
                total_samples += len(samples)
                name = array_name(subtype_key, direction, edge)
                emit_array(lines, name, samples)
                entries.append((subtype_key, direction, edge, name))

    lines.append("}  // namespace")
    lines.append("")
    lines.append("const BeepClip* findBeepClip(const std::string& subtype, bool local, bool start) {")
    lines.append("    static const struct { const char* subtype; bool local; bool start; BeepClip clip; } kTable[] = {")
    for subtype_key, direction, edge, name in entries:
        local_lit = "true" if direction == "local" else "false"
        start_lit = "true" if edge == "start" else "false"
        lines.append(f"        {{\"{subtype_key}\", {local_lit}, {start_lit}, {{{name}, {name}Count}}}},")
    lines.append("    };")
    lines.append("")
    lines.append("    for (const auto& row : kTable) {")
    lines.append("        if (row.local == local && row.start == start && subtype == row.subtype) return &row.clip;")
    lines.append("    }")
    lines.append("    return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace voice")
    lines.append("}  // namespace tfrs")
    lines.append("")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_PATH} ({total_samples} total samples, {len(entries)} clips)")


if __name__ == "__main__":
    main()
